/*
Navicat MySQL Data Transfer

Source Server         : mysql
Source Server Version : 80020
Source Host           : localhost:3306
Source Database       : palindrome

Target Server Type    : MYSQL
Target Server Version : 80020
File Encoding         : 65001

Date: 2021-03-22 12:16:32
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for palindrome
-- ----------------------------
DROP TABLE IF EXISTS `palindrome`;
CREATE TABLE `palindrome` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `longest_palindrome` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `original` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK1p88ovjhnb96t0cf5fmerl1hl` (`original`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of palindrome
-- ----------------------------
INSERT INTO `palindrome` VALUES ('1', 'kljlk', 'klajsdfkljlkdsajgflauoitjakgmlkajglja;dksfj;lkdsajf;lkjas;kgjoiaweuroasdfjlkajsdkl');
INSERT INTO `palindrome` VALUES ('2', 'anana', 'bananas');
INSERT INTO `palindrome` VALUES ('3', 'cbababc', '\"abbcccbbbcaaccbababcbcabca\"');
INSERT INTO `palindrome` VALUES ('4', 'cbababc', 'abbcccbbbcaaccbababcbcabca');
INSERT INTO `palindrome` VALUES ('5', 'bacab', '\"abacab\"');
INSERT INTO `palindrome` VALUES ('6', '\"nrakjvyjdmwkgyknrbtarcuiymxgltnefhxzebzfwuvjhudnbhssysbhvwqgsbkhzayquhhamlfkevbrmvuxlxnrmnnhkctckktvcirkvbbcndxuqojlsvxvgfslkukcsplxalfscreenyzziwahyohelaotyvriaalkyhcatmiwlduwpewljjihkebpuawfemolgiitoljqyizkfeimvjdqpxiiwfnrjblnzxywyicmuckrzvxwxpdqqkrkjuohtuuthoujkrkqqdpxwxvzrkcumciywyxznlbjrnfwiixpqdjvmiefkziyqjlotiiglomefwaupbekhijjlwepwudlwimtachyklaairvytoalehoyhawizzyneercsflaxlpsckuklsfgvxvsljoquxdncbbvkricvtkkctckhnnmrnxlxuvmrbvekflmahhuqyazhkbsgqwvhbsysshbnduhjvuwfzbezxhfentlgxmyiucratbrnkygkwmdjyvjkarn\"', '\"nrakjvyjdmwkgyknrbtarcuiymxgltnefhxzebzfwuvjhudnbhssysbhvwqgsbkhzayquhhamlfkevbrmvuxlxnrmnnhkctckktvcirkvbbcndxuqojlsvxvgfslkukcsplxalfscreenyzziwahyohelaotyvriaalkyhcatmiwlduwpewljjihkebpuawfemolgiitoljqyizkfeimvjdqpxiiwfnrjblnzxywyicmuckrzvxwxpdqqkrkjuohtuuthoujkrkqqdpxwxvzrkcumciywyxznlbjrnfwiixpqdjvmiefkziyqjlotiiglomefwaupbekhijjlwepwudlwimtachyklaairvytoalehoyhawizzyneercsflaxlpsckuklsfgvxvsljoquxdncbbvkricvtkkctckhnnmrnxlxuvmrbvekflmahhuqyazhkbsgqwvhbsysshbnduhjvuwfzbezxhfentlgxmyiucratbrnkygkwmdjyvjkarn\"');
INSERT INTO `palindrome` VALUES ('7', 'nrakjvyjdmwkgyknrbtarcuiymxgltnefhxzebzfwuvjhudnbhssysbhvwqgsbkhzayquhhamlfkevbrmvuxlxnrmnnhkctckktvcirkvbbcndxuqojlsvxvgfslkukcsplxalfscreenyzziwahyohelaotyvriaalkyhcatmiwlduwpewljjihkebpuawfemolgiitoljqyizkfeimvjdqpxiiwfnrjblnzxywyicmuckrzvxwxpdqqkrkjuohtuuthoujkrkqqdpxwxvzrkcumciywyxznlbjrnfwiixpqdjvmiefkziyqjlotiiglomefwaupbekhijjlwepwudlwimtachyklaairvytoalehoyhawizzyneercsflaxlpsckuklsfgvxvsljoquxdncbbvkricvtkkctckhnnmrnxlxuvmrbvekflmahhuqyazhkbsgqwvhbsysshbnduhjvuwfzbezxhfentlgxmyiucratbrnkygkwmdjyvjkarn', 'nrakjvyjdmwkgyknrbtarcuiymxgltnefhxzebzfwuvjhudnbhssysbhvwqgsbkhzayquhhamlfkevbrmvuxlxnrmnnhkctckktvcirkvbbcndxuqojlsvxvgfslkukcsplxalfscreenyzziwahyohelaotyvriaalkyhcatmiwlduwpewljjihkebpuawfemolgiitoljqyizkfeimvjdqpxiiwfnrjblnzxywyicmuckrzvxwxpdqqkrkjuohtuuthoujkrkqqdpxwxvzrkcumciywyxznlbjrnfwiixpqdjvmiefkziyqjlotiiglomefwaupbekhijjlwepwudlwimtachyklaairvytoalehoyhawizzyneercsflaxlpsckuklsfgvxvsljoquxdncbbvkricvtkkctckhnnmrnxlxuvmrbvekflmahhuqyazhkbsgqwvhbsysshbnduhjvuwfzbezxhfentlgxmyiucratbrnkygkwmdjyvjkarn');
INSERT INTO `palindrome` VALUES ('8', 'dytyd', 'sxxxrjgrirnkkiafhdlzirazovyyutbysmteztuhezmfmrxwbsklykwukesocrprvlezocszhmpmfakxjxawsxirefkhoalqmgwqqgeemdvjigvmtorzobfqnkqrdytydglfvcinnhagehieoxpvufeutlmcgcsplwnaqmrtqtmxyrf');
INSERT INTO `palindrome` VALUES ('9', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');
INSERT INTO `palindrome` VALUES ('11', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n');
